name: C/C++ CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Cache submodules
      uses: actions/cache@v2
      env:
        cache-name: cache-submodules
      with:
        path: |
          libs/antlr4
          libs/CLI11
          libs/llvm
          libs/whereami
        key: ${{ runner.os }}-submodules-${{ hashFiles('**/*') }}
        restore-keys: |
          ${{ runner.os }}-submodules-${{ env.cache-name }}-
          ${{ runner.os }}-submodules-

    - name: Install uuid package
      run: sudo apt-get install uuid-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --parallel

    - name: Cache build files
      uses: actions/cache@v2
      env:
        cache-name: cache-build
      with:
        path: build
        key: ${{ runner.os }}-build-${{ hashFiles('**/*') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
